services:
  - type: web
    name: bantu-sesama-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --dns-result-order=ipv4first
      - key: TRUST_PROXY
        value: "1"
      - key: DATABASE_SSL
        value: "true"
      - key: DB_SYNC
        value: "false"
      - key: CORS_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_IS_PRODUCTION
        value: "false"